# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDApplication
  pod 'SDWebImageSwiftUI'
  
  target 'TMDApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDApplicationUITests' do
    # Pods for testing
  end

end
